import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'all_news_model_v2.freezed.dart';
// optional: Since our AllNewsModelV2 class is serializable, we must add this line.
// But if AllNewsModelV2 was not serializable, we could skip it.
part 'all_news_model_v2.g.dart';

@freezed
@JsonSerializable()
class AllNewsModelV2 with _$AllNewsModelV2 {
  const AllNewsModelV2({
    required this.firstName,
    required this.lastName,
    required this.age,
  });

  final String firstName;
  final String lastName;
  final int age;

  factory AllNewsModelV2.fromJson(Map<String, Object?> json) => _$AllNewsModelV2FromJson(json);

  Map<String, Object?> toJson() => _$AllNewsModelV2ToJson(this);
}
